@baseUrl = http://localhost:3333
@thisUrl = {{baseUrl}}/appointments
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc4OTA4ODIsImV4cCI6MTYwMDQ4Mjg4Miwic3ViIjoiNzU5MWRkNWQtZWZjNi00MDhmLTg4N2MtNzg0MzY5MjljNDNmIn0.oZnKES1Sr4ahurfa08697kxWOP-WqAmTLtNrESK-bf0


### Get appointments
{{thisUrl}}
content-type: application/json
Authorization: Bearer {{token}}

###
POST {{thisUrl}}
content-type: application/json
Authorization: Bearer {{token}}

{
  "provider_id": "08968bf6-8320-4d8b-9c9f-277f71fb6be1",
  "date" : "{{$datetime iso8601}}"
}

###
{{baseUrl}}/providers/7591dd5d-efc6-408f-887c-78436929c43f/month-availability/?year=2020&month=9
Authorization: Bearer {{token}}
