### User Variables
  @providerId = {{provider.response.body.user.id}}
  @providerToken = {{provider.response.body.token}}
  @clientId = {{client.response.body.user.id}}
  @clientToken = {{client.response.body.token}}
# @name provider
POST {{baseUrl}}/sessions
  Content-Type: application/json

  {
    "email": "{{providerEmail}}",
    "password": "{{providerPassword}}"
  }

###
# @name client
POST {{baseUrl}}/sessions
  Content-Type: application/json

  {
    "email": "{{clientEmail}}",
    "password": "{{clientPassword}}"
  }

###
###
@forgotEmailToken = 062078f7-c506-430b-a7c1-a85deccfba7c
### Forgot
POST {{baseUrl}}/password/forgot
  Content-Type: application/json

  {
    "email": "{{clientEmail}}"
  }
###
POST {{baseUrl}}/password/reset
  Content-Type: application/json

  {
    "token": "{{forgotEmailToken}}",
    "password": "{{clientPassword}}",
    "password_confirmation": "{{clientPassword}}"
  }
###
