### User Variables
  @providerId = {{provider.response.body.user.id}}
  @providerToken = {{provider.response.body.token}}
  @clientId = {{client.response.body.user.id}}
  @clientToken = {{client.response.body.token}}
# @name provider
POST {{baseUrl}}/sessions
  Content-Type: application/json

  {
    "email": "{{providerEmail}}",
    "password": "{{providerPassword}}"
  }

###
# @name client
POST {{baseUrl}}/sessions
  Content-Type: application/json

  {
    "email": "{{clientEmail}}",
    "password": "{{clientPassword}}"
  }

###
@tomorowYear = {{$datetime "YYYY" 1 d}}
@tomorowMonth = {{$datetime "MM" 1 d}}
@tomorowDay = {{$datetime "DD" 1 d}}

###
GET {{baseUrl}}/providers
Authorization: Bearer {{providerToken}}

###
GET {{baseUrl}}/providers/{{providerId}}/month-availability
  ?year={{tomorowYear}}
  &month={{tomorowMonth}}
Authorization: Bearer {{clientToken}}

###
GET {{baseUrl}}/providers/{{providerId}}/day-availability
  ?year={{tomorowYear}}
  &month={{tomorowMonth}}
  &day={{tomorowDay}}
Authorization: Bearer {{providerToken}}
