### User Variables
  @providerId = {{provider.response.body.user.id}}
  @providerToken = {{provider.response.body.token}}
  @clientId = {{client.response.body.user.id}}
  @clientToken = {{client.response.body.token}}
# @name provider
POST {{baseUrl}}/sessions
  Content-Type: application/json

  {
    "email": "{{providerEmail}}",
    "password": "{{providerPassword}}"
  }

###
# @name client
POST {{baseUrl}}/sessions
  Content-Type: application/json

  {
    "email": "{{clientEmail}}",
    "password": "{{clientPassword}}"
  }

###
###
