@baseUrl = http://localhost:3333
@thisUrl = {{baseUrl}}/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc5NDAxMzEsImV4cCI6MTYwMDUzMjEzMSwic3ViIjoiYTdiYjAzNjgtMWVhYy00N2UwLWIwZWYtODMzODkxYWI5NDUwIn0.ZOARytcFxXOtSTlyKUvApTKYqYMNp1CmrWBMQKVNPNY

### Register
POST {{thisUrl}}
Content-Type: application/json

{
  "name": "Pedro Moreno",
  "email": "pedro@teste.com",
  "password": "test123"
}

###
PATCH {{thisUrl}}/avatar
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: application/octet-stream

< ./tmp/avatar.jpg
--MyBoundary--







