@baseUrl = http://localhost:3333
@thisUrl = {{baseUrl}}/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc4MDQ3NjEsImV4cCI6MTYwMDM5Njc2MSwic3ViIjoiNzU5MWRkNWQtZWZjNi00MDhmLTg4N2MtNzg0MzY5MjljNDNmIn0.3h7h-Vi1vut6oCzq0I8gcHTnSjIWcvZE_tevK1Kee0Q

### Register
POST {{thisUrl}}
Content-Type: application/json

{
  "name": "Pedro Moreno",
  "email": "pedro@teste.com",
  "password": "test123"
}

###
PATCH {{thisUrl}}/avatar
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer {{token}}

--MyBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: application/octet-stream

< ./tmp/avatar.jpg
--MyBoundary--







